version: 0.0
os: linux
files:
  - source: /
    destination: /test
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
#     - location: scripts/start_server
#       timeout: 300
#       runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server
  #     timeout: 300
  #     runas: root
