version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/

permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: /
      timeout: 300
      runas: root
      commands:
        - echo "Before Install: This is a before install script" > /home/ubuntu/before_install.log
  AfterInstall:
    - location: /
      timeout: 300
      runas: root
      commands:
        - echo "After Install: This is an after install script" > /home/ubuntu/after_install.log