version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - sh install_driver.sh
  build:
    commands:
      - npm test
      
reports: #New
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports 
  