version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - sh install_driver.sh
  build:
    commands:
      - npm test

reports: 
  SurefireReports: 
    files: 
      - polymer/mochawesome-report/mochawesome.json
    base-directory: 'polymer/mochawesome-report' 
  