version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install  # Install project dependencies

  pre_build:
    commands:
      # Set up Selenium WebDriver (assuming WebDriver is already installed)
      - webdriver-manager update --versions.standalone=4.0.0 --gecko=false --quiet
      # Start Selenium server in background
      - nohup webdriver-manager start --versions.standalone=4.0.0 --gecko=false > /dev/null 2>&1 &
      # Wait for Selenium server to start
      - sleep 5
      # Additional pre-build commands if needed

  build:
    commands:
      # Run Selenium tests
      - npm test

  post_build:
    commands:
      # Additional post-build commands if needed

artifacts:
  files:
    # Specify any files to be deployed as artifacts, if needed
