version: 0.2


phases:
  install:
    commands:
       - apt-get install curl
       - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&\
       - apt-get install nodejs
       - npm install
       
       - npm install -g webdriver-manager
       - webdriver-manager update
       - npm install selenium-webdriver@4.16.0

       - npm install mocha@10.2.0
       - npm install mochawesome@7.1.3
       - npm install selenium@2.20.0
       - npm install webdriver@8.27.0
       - sh install_driver.sh
       - npm install chromedriver 
       
      
      
       
  build:
    commands:
       - npm test
      
      
     
      
      