version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - sh install_driver.sh
  build:
    commands:
    #  - npm test
      - npm surefire-report:report
reports: 
  SurefireReports: 
    files: 
      - 'mochawesome-report/mochawesome.json'
      - 'mochawesome-report/mochawesome.html'
    