version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - sh install_driver.sh
      - npm install -g mochawesome mochawesome-report-generator
  build:
    commands:
      - npm test
      - mocha --no-timeouts 'main/index.js' --reporter mochawesome
reports: 
  SurefireReports: 
    files: 
      - 'mochawesome-report/mochawesome.json'
      - 'mochawesome-report/mochawesome.html'
    