version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install  # Install project dependencies

  pre_build:
    commands:
      # Start Chromedriver in background
      - chromedriver --url-base=/wd/hub --port=4444 > /dev/null 2>&1 &
      # Wait for Chromedriver to start
      - sleep 5
      # Additional pre-build commands if needed

  build:
    commands:
      # Run Mocha tests with Mochawesome reporter
      - npm test

  post_build:
    commands:
      # Additional post-build commands if needed

artifacts:
  files:
    # Specify any files to be deployed as artifacts, if needed
