version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get -y update
      - apt-get -y install google-chrome-stable

  build:
    commands:
      - npm test || exit 0
reports: 
  TestingReports: 
    files: 
      - '**/*'
      
    