version: 0.2


phases:
  install:
    commands:
       - apt-get install curl
       - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&\
       - apt-get install nodejs
       
       - sh install_driver.sh    
       
       - npm install -g webdriver-manager
       - webdriver-manager update
       - npm install selenium-webdriver@4.16.0
      
       - npm install mocha@10.2.0
       - npm install mochawesome@7.1.3
       - npm install selenium@2.20.0
       - npm install webdriver@8.27.0
            
  build:
    commands:
       - npm test
      
reports:
 java_reports:
   files:
     - java_reports.xml
   base-directory: java_reports/
   file-format: JUNITXML