version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - sh install_driver.sh
  build:
    commands:
      - npm test
      
reports: 
  SurefireReports: 
    files: 
      - 'mochawesome-report/mochawesome.json'
      - 'mochawesome-report/mochawesome.html'
    #base-directory: '/codebuild/output/src3133932211/src/mochawesome-report/'  
  