version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install  # Install project dependencies
      # Install necessary dependencies for running Chrome in headless mode
      - sudo apt-get update
      - sudo apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 xdg-utils

  pre_build:
    commands:
      # Start Chromedriver in headless mode
      - chromedriver --url-base=/wd/hub --port=4444 --headless --no-sandbox > /dev/null 2>&1 &
      # Wait for Chromedriver to start
      - sleep 5
      # Additional pre-build commands if needed

  build:
    commands:
      # Run Mocha tests with Mochawesome reporter
      - npm test

  post_build:
    commands:
      # Additional post-build commands if needed

artifacts:
  files:
    # Specify any files to be deployed as artifacts, if needed
