#!/bin/bash
set -x
# service httpd start

# npm test

# cd /test
# npm i
# npm test || exit 1

#npm test || exit 1
# whoami
# pwd
cd /test
#pwd
export DISPLAY=:10.0
echo "$DISPLAY"
sudo chmod 777 /test/mochawesome-report
npm test || exit 0
sudo rm -rf /var/www/html/*
sudo cp -r /test/* /var/www/html/
useradd shubham

